Portfolio details popup window
Yulianav09/Portfolio pull request #16
Opened 2023-06-22 15:52 UTC by Yulianav09

### Portfolio details popup window

- Added a popup window for projects cards
- Cards are generated dynamically 
- popup window shows the information of the selected project

2023-06-22 16:55 UTC, shahadat3669 requested changes
Hi Everyone, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media4.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif"/>

## Highlights
✅ Good PR Title
✅ Good PR Description
✅ Good use of GitHub Flows

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Have any doubt ❓


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

## ⚠️ WARNING ⚠️
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-22 16:55 UTC, shahadat3669 commented on index.html
> +            <a target="_blank" id="source" href=""><button class="projectButton icons"><span>See source</span><img src="./src/Icon -GitHub.svg" alt=""></button></a>
- [x] Well! Your button looks good. 👍 Currently, the gap between buttons is "12px", but as per the design, there should be a "24px" gap. Please consider updating the code to increase the gap between the buttons to match the design specifications. 🙏 
- [x] Additionally, it is not necessary to wrap the button tag with the "a" tag. You should choose either the "a" tag or the button tag, but using both is not necessary. Please update the code accordingly to ensure consistency and simplify the markup. 🙏

By making these adjustments, you will ensure better adherence to the design and improve the overall user experience.  Good luck with the updates! 💪🔧🎨

2023-06-22 16:55 UTC, shahadat3669 commented on index.html
> +      </article>
- [x] Well! Your model looks good. 👍 Currently, the padding is  "16px", but per the design, there should be a "24px". Please consider updating the code to increase the padding to match the design specifications. 🙏

2023-06-22 16:55 UTC, shahadat3669 commented on index.html
> +        </ul>
- [x] Well! Your tags' color and font styles look good. 👍 Currently, the gap between tags is "12px", but as per the design, there should be an "8px" gap. Please consider updating the code to reduce the gap between the tags to match the design specifications. 🙏💻

By making this adjustment, you will ensure better alignment and spacing of the tags, creating a more visually pleasing layout that aligns with the design guidelines. ✨🚀

2023-06-22 22:51 UTC, merged

2023-06-23 00:31 UTC, Yulianav09 commented
Hello @shahadat3669, thanks for the feedback, all the changes were applied